default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 7866
  host: localhost
  port: 5432

development:
  <<: *default
  database: PennyPincher_development
test:
  <<: *default
  database: PennyPincher_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
